#include<stdio.h>
#include<stdlib.h>
#include<sys/types.h>
#include<unistd.h>
#include<signal.h>
#include<sys/resource.h>
#include<sys/stat.h>
#include<sys/timeb.h>
#include<time.h>
#include<pwd.h>
#include<grp.h>
#include<string.h>
#include<dirent.h>
//#include<linux/dirent.h>
#include<linux/types.h>
#include<fcntl.h>
#include<utime.h>
#include<sys/msg.h>
#include<sys/ipc.h>
#include<pthread.h>
